---
- name: Check git present
  ansible.builtin.package:
    name: git
    state: present

- name: Clone lighthouse repo
  ansible.builtin.git:
    repo: "{{ lighthouse_git }}"
    dest: "{{ lighthouse_dest }}"
